import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import Layout from "../components/layout/Layout/Layout";

export default function Home() {
  const [pokemonList, setPokemonList] = useState([]);
  const [url, setUrl] = useState(
    `https://pokeapi.co/api/v2/pokemon/?limit=20&offset=0`
  );
  const [loading, setLoading] = useState(false);
  const [total, setTotal] = useState("0");
  const [previousPage, setPreviousPage] = useState();
  const [nextPage, setNextPage] = useState();

  useEffect(() => {
    const getData = async () => {
      setLoading(true);
      const res = await axios.get(url);
      setTotal(Math.ceil(res.data.count / 20));
      setPreviousPage(res.data.previous);
      setNextPage(res.data.next);
      setPokemonList(res.data.results);
      setLoading(false);
    };
    getData();
  }, [url]);

  return (
    <div>
      <Head>
        <title>Pokemon App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {pokemonList.map((pokemon) => {
          return <div key={pokemon.url}>{pokemon.name}</div>;
        })}
      </Layout>
    </div>
  );
}
