import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import Layout from "../components/layout/Layout/Layout";
import Gallery from "../components/layout/Gallery/Gallery";
import Card from "../components/molecules/Card/Card";
import Paginator from "../components/molecules/Paginator/Paginator";

export default function Home() {
  const [pokemonList, setPokemonList] = useState([]);
  const [url, setUrl] = useState(
    `https://pokeapi.co/api/v2/pokemon/?limit=20&offset=0`
  );
  const [loading, setLoading] = useState(false);
  const [total, setTotal] = useState("0");
  const [previousPage, setPreviousPage] = useState();
  const [page, setPage] = useState(1);
  const [nextPage, setNextPage] = useState();

  const getPokemonData = async (data) => {
    data.map(async (pokemon) => {
      const result = await axios.get(pokemon.url);
      setPokemonList((state) => {
        state = [...state, result.data];
        state.sort((a, b) => (a.id > b.id ? 1 : -1));
        return state;
      });
    });
  };

  const handlePreviousPageButton = () => {
    setPokemonList([]);
    setUrl(previousPage);
    setPage(Math.max(page - 1, 0));
  };

  const handleNextPageButton = () => {
    setPokemonList([]);
    setUrl(nextPage);
    setPage(Math.min(page + 1, total - 1));
  };

  useEffect(() => {
    const getData = async () => {
      setLoading(true);
      const res = await axios.get(url);
      setTotal(Math.ceil(res.data.count / 20));
      setPreviousPage(res.data.previous);
      setNextPage(res.data.next);
      getPokemonData(res.data.results);
      setLoading(false);
    };
    getData();
  }, [url]);

  return (
    <div className="py-4">
      <Head>
        <title>Pokemon App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Paginator
          totalPages={total}
          page={page}
          previousPageButton={handlePreviousPageButton}
          previousButtonDisabled={!previousPage}
          nextPageButton={handleNextPageButton}
          nexButtonDisabled={!nextPage}
        />

        <Gallery>
          <Card pokemonData={pokemonList} loading={loading} />
        </Gallery>

        <Paginator
          totalPages={total}
          page={page}
          previousPageButton={handlePreviousPageButton}
          previousButtonDisabled={!previousPage}
          nextPageButton={handleNextPageButton}
          nexButtonDisabled={!nextPage}
        />
      </Layout>
    </div>
  );
}
